### ISSUE TITLE
redis-shake同步redis5.03报unknown object-type 0f

### ISSUE THREAD

**Issue by zhouhongsheng1** [aliyun/RedisShake#3]
redis source:5.0.3
redis target:5.0.3
数据类型：zset、string(bitmap)、list、stream、set

1) "client-output-buffer-limit"
2) "normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60"

启动redis-shake同步时报错：

2019/03/11 06:07:22 [INFO] redis-shake configuration: {"Id":"redis-shake","LogFile":"","SystemProfile":9310,"HttpProfile":9320,"NCpu":0,"Parallel":4,"InputRdb":"local_dump","OutputRdb":"local_dump","SourceAddress":"xxxxxx:6666","SourcePasswordRaw":"","SourcePasswordEncoding":"","SourceVersion":7,"SourceAuthType":"","TargetAddress":"xxxxxx:6667","TargetPasswordRaw":"","TargetPasswordEncoding":"","TargetVersion":7,"TargetDB":-1,"TargetAuthType":"","FakeTime":"","Rewrite":true,"FilterDB":"","FilterKey":[],"FilterSlot":[],"BigKeyThreshold":524288000,"Psync":false,"Metric":true,"MetricPrintLog":true,"HeartbeatUrl":"","HeartbeatInterval":3,"HeartbeatExternal":"test external","HeartbeatNetworkInterface":"","SenderSize":104857600,"SenderCount":5000,"SenderDelayChannelSize":65535,"ReplaceHashTag":false,"ExtraInfo":false,"SockFileName":"","SockFileSize":0,"HeartbeatIp":"127.0.0.1","ShiftTime":0,"TargetRedisVersion":"5.0.3","TargetReplace":false}
2019/03/11 06:07:22 [INFO] sync from 'xxxxxx:6666' to 'xxxxxx:6667' http '9320'
2019/03/11 06:07:22 [INFO] sync from 'xxxxxx:6666' to 'xxxxxx:6667'
2019/03/11 06:07:22 [INFO] rdb file = 1134
2019/03/11 06:07:22 [INFO] Aux information key:redis-ver value:5.0.3
2019/03/11 06:07:22 [INFO] Aux information key:redis-bits value:64
2019/03/11 06:07:22 [INFO] Aux information key:ctime value:1552298842
2019/03/11 06:07:22 [INFO] Aux information key:used-mem value:1906512
2019/03/11 06:07:22 [INFO] Aux information key:repl-stream-db value:0
2019/03/11 06:07:22 [INFO] Aux information key:repl-id value:7ca1a84deb8c4b7946355938c834fddd40098e61
2019/03/11 06:07:22 [INFO] Aux information key:repl-offset value:6917447
2019/03/11 06:07:22 [INFO] Aux information key:aof-preamble value:0
2019/03/11 06:07:22 [INFO] db_size:26 expire_size:1
2019/03/11 06:07:22 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client outout buffer oom, if so set output buffer larger.
[error]: unknown object-type 0f
    2   /home/soft/redis-shake/src/pkg/rdb/reader.go:98
            pkg/rdb.(*rdbReader).readObjectValue
    1   /home/soft/redis-shake/src/pkg/rdb/loader.go:169
            pkg/rdb.(*Loader).NextBinEntry
    0   /home/soft/redis-shake/src/redis-shake/common/utils.go:763
            redis-shake/common.NewRDBLoader.func1
        ... ...
[stack]: 
    0   /home/soft/redis-shake/src/redis-shake/common/utils.go:764
            redis-shake/common.NewRDBLoader.func1
        ... ...

**Comment by vinllen** [comment]
stream的新特性的兼容目前有问题，我最近支持一下

**Comment by vinllen** [comment]
5.0 stream类型已经支持，但有需要注意的点，请参考：[这里](https://github.com/aliyun/redis-shake/issues/4)。

**Comment by vinllen** [comment]
5.0版本同步到低版本，如果使用了新特性stream，将直接抛出异常。
